package com.caits.modules.transactions;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

public final class TxnDtos {
    private TxnDtos() {}

    public record LineRequest(
            Integer srNo,
            Integer itemId,
            Integer uomId,
            BigDecimal orderedQty,
            BigDecimal receivedQty,
            BigDecimal acceptedQty,
            BigDecimal rejectedQty,
            BigDecimal requestedQty,
            BigDecimal qty,
            BigDecimal availableStock,
            BigDecimal amount,
            BigDecimal rate,
            BigDecimal mrp,
            String batchLotNo,
            LocalDate mfgDate,
            LocalDate expiryDate,
            Integer locationId,
            String locationBin,
            String itemCondition,
            String serialNo,
            String ipAddress,
            String macAddress,
            String hostname,
            Integer issuedToEmpId,
            String remark
    ) {}

    public record DocumentRequest(
            String docType,
            LocalDate docDate,
            LocalDate postingDate,
            LocalDate requiredByDate,
            Integer entityId,
            Integer locationId,
            Integer fromLocationId,
            Integer toLocationId,
            Integer partyId,
            String partyAdd,
            String partyContactPerson,
            String partyPhone,
            String partyGstin,
            String shipTo,
            Integer departmentId,
            Integer initiatedByEmpId,
            String employeeRefCode,
            String designation,
            String docSubtype,
            String returnFlag,
            Integer refTxnHeaderId,
            String referenceNo,
            String invoiceNo,
            LocalDate invoiceDate,
            String poNo,
            LocalDate poDate,
            String purpose,
            String attachmentUrl,
            String attachmentName,
            Integer inspectedByEmpId,
            LocalDate inspectionDate,
            Integer handedOverToEmpId,
            String handoverDesignation,
            LocalDate handoverDate,
            Integer receivedByEmpId,
            String receivedByName,
            String receivedDesignation,
            LocalDate receivedDate,
            String conditionOnReturn,
            Integer preparedByEmpId,
            LocalDate preparedDate,
            Integer approvedByEmpId,
            LocalDate approvedDate,
            BigDecimal totalOrderedQty,
            BigDecimal totalReceivedQty,
            BigDecimal totalAcceptedQty,
            BigDecimal totalRejectedQty,
            BigDecimal totalPendingQty,
            BigDecimal totalAmount,
            String footerRemark,
            String remarks,
            String docSubmitAction,
            List<LineRequest> lines
    ) {}

    public record LineResponse(
            Integer detailId,
            Integer srNo,
            Integer itemId,
            String itemCode,
            String itemName,
            String itemType,
            Integer uomId,
            String uomCode,
            BigDecimal orderedQty,
            BigDecimal receivedQty,
            BigDecimal acceptedQty,
            BigDecimal rejectedQty,
            BigDecimal requestedQty,
            BigDecimal qty,
            BigDecimal availableStock,
            BigDecimal amount,
            BigDecimal rate,
            BigDecimal mrp,
            String batchLotNo,
            LocalDate mfgDate,
            LocalDate expiryDate,
            Integer locationId,
            String locationBin,
            String itemCondition,
            String serialNo,
            String ipAddress,
            String macAddress,
            String hostname,
            Integer issuedToEmpId,
            String remark,
            Integer blsId
    ) {}

    public record DocumentResponse(
            Integer docId,
            String docNo,
            String docType,
            LocalDate docDate,
            LocalDate postingDate,
            LocalDate requiredByDate,
            Integer entityId,
            Integer locationId,
            Integer fromLocationId,
            Integer toLocationId,
            Integer partyId,
            String partyAdd,
            String partyContactPerson,
            String partyPhone,
            String partyGstin,
            String shipTo,
            Integer departmentId,
            Integer initiatedByEmpId,
            String employeeRefCode,
            String designation,
            String docSubtype,
            String returnFlag,
            Integer refTxnHeaderId,
            String referenceNo,
            String invoiceNo,
            LocalDate invoiceDate,
            String poNo,
            LocalDate poDate,
            String purpose,
            String attachmentUrl,
            String attachmentName,
            Integer inspectedByEmpId,
            LocalDate inspectionDate,
            Integer handedOverToEmpId,
            String handoverDesignation,
            LocalDate handoverDate,
            Integer receivedByEmpId,
            String receivedByName,
            String receivedDesignation,
            LocalDate receivedDate,
            String conditionOnReturn,
            Integer preparedByEmpId,
            LocalDate preparedDate,
            Integer approvedByEmpId,
            LocalDate approvedDate,
            BigDecimal totalOrderedQty,
            BigDecimal totalReceivedQty,
            BigDecimal totalAcceptedQty,
            BigDecimal totalRejectedQty,
            BigDecimal totalPendingQty,
            BigDecimal totalAmount,
            String footerRemark,
            String remarks,
            String status,
            String createdBy,
            java.time.LocalDateTime createdOn,
            String message,
            List<LineResponse> lines
    ) {}

    public record ListItem(
            Integer docId,
            String docNo,
            String docType,
            LocalDate docDate,
            LocalDate postingDate,
            LocalDate requiredByDate,
            Integer entityId,
            Integer locationId,
            Integer fromLocationId,
            Integer toLocationId,
            Integer partyId,
            Integer departmentId,
            Integer initiatedByEmpId,
            Integer refTxnHeaderId,
            String referenceNo,
            String invoiceNo,
            Integer totalItems,
            BigDecimal totalAmount,
            String status,
            String docSubtype,
            String returnFlag,
            String attachmentUrl,
            String attachmentName,
            java.time.LocalDateTime createdOn,
            java.time.LocalDateTime modifiedOn
    ) {}

    public record ApproveRequest(Integer approvedByEmpId, String remarks) {}

    public record RejectRequest(String reason) {}

    /** Item IDs currently allotted to an employee (Material Return item picker). */
    public record AllottedItemsResponse(List<Integer> itemIds) {}
}
