-- Dedicated Department master with Head of Department (replaces GTY-DEPT genmaster for transactions/HR).
SET search_path TO caits_local;

-- ---------------------------------------------------------------------------
-- 1) Department table
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS hrc_department_mst (
    dept_department_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_department_code    VARCHAR(20)  NOT NULL,
    dept_department_name    VARCHAR(100) NOT NULL,
    dept_entity_id_ent      INTEGER      NOT NULL,
    dept_head_emp_id_emp    INTEGER,
    dept_desc               VARCHAR(250),
    dept_isactive           BOOLEAN      NOT NULL DEFAULT TRUE,
    dept_created_by         VARCHAR(50),
    dept_created_on         TIMESTAMP    NOT NULL DEFAULT NOW(),
    dept_modified_by        VARCHAR(50),
    dept_modified_on        TIMESTAMP,
    CONSTRAINT uq_dept_code UNIQUE (dept_department_code),
    CONSTRAINT fk_dept_entity FOREIGN KEY (dept_entity_id_ent) REFERENCES org_entity_mst (ent_entity_id),
    CONSTRAINT fk_dept_head_emp FOREIGN KEY (dept_head_emp_id_emp) REFERENCES hrc_employee_mst (emp_employee_id)
);

-- ---------------------------------------------------------------------------
-- 2) Seed departments from existing GTY-DEPT genmaster (if present)
-- ---------------------------------------------------------------------------
INSERT INTO hrc_department_mst (
    dept_department_code,
    dept_department_name,
    dept_entity_id_ent,
    dept_isactive,
    dept_created_by,
    dept_created_on
)
SELECT
    m.gmst_value_code,
    m.gmst_value_name,
    e.ent_entity_id,
    COALESCE(m.gmst_isactive, TRUE),
    'system',
    NOW()
FROM genmaster_mst m
JOIN gentype_mst t ON t.gtyp_gentype_id = m.gmst_gentype_id_gtyp
CROSS JOIN (
    SELECT ent_entity_id
    FROM org_entity_mst
    WHERE ent_isactive = TRUE
    ORDER BY ent_entity_id
    LIMIT 1
) e
WHERE UPPER(t.gtyp_type_code) = 'GTY-DEPT'
  AND NOT EXISTS (
      SELECT 1 FROM hrc_department_mst d WHERE UPPER(d.dept_department_code) = UPPER(m.gmst_value_code)
  );

-- Fallback seed when no genmaster rows exist
INSERT INTO hrc_department_mst (
    dept_department_code, dept_department_name, dept_entity_id_ent, dept_isactive, dept_created_by, dept_created_on
)
SELECT v.code, v.name, e.ent_entity_id, TRUE, 'system', NOW()
FROM (VALUES
    ('DEPT-IT', 'IT'),
    ('DEPT-STORES', 'Stores'),
    ('DEPT-OPS', 'Operations'),
    ('DEPT-ADMIN', 'Admin'),
    ('DEPT-FIN', 'Finance'),
    ('DEPT-HR', 'HR'),
    ('DEPT-MAINT', 'Maintenance'),
    ('DEPT-PROD', 'Production')
) AS v(code, name)
CROSS JOIN (
    SELECT ent_entity_id FROM org_entity_mst WHERE ent_isactive = TRUE ORDER BY ent_entity_id LIMIT 1
) e
WHERE NOT EXISTS (SELECT 1 FROM hrc_department_mst);

-- ---------------------------------------------------------------------------
-- 3) Transactions: FK to department master
-- ---------------------------------------------------------------------------
ALTER TABLE txn_header_mst
    ADD COLUMN IF NOT EXISTS txh_department_id_dept INTEGER;

UPDATE txn_header_mst h
SET txh_department_id_dept = d.dept_department_id
FROM genmaster_mst m
JOIN hrc_department_mst d ON UPPER(d.dept_department_code) = UPPER(m.gmst_value_code)
WHERE h.txh_department_id_gmst = m.gmst_genmaster_id
  AND h.txh_department_id_dept IS NULL;

ALTER TABLE txn_header_mst DROP COLUMN IF EXISTS txh_department_id_gmst;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_txh_department_dept'
    ) THEN
        ALTER TABLE txn_header_mst
            ADD CONSTRAINT fk_txh_department_dept
            FOREIGN KEY (txh_department_id_dept) REFERENCES hrc_department_mst (dept_department_id);
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- 4) Employees: FK to department master
-- ---------------------------------------------------------------------------
ALTER TABLE hrc_employee_mst
    ADD COLUMN IF NOT EXISTS emp_department_id_dept INTEGER;

UPDATE hrc_employee_mst e
SET emp_department_id_dept = d.dept_department_id
FROM hrc_department_mst d
WHERE e.emp_department IS NOT NULL
  AND TRIM(e.emp_department) <> ''
  AND UPPER(TRIM(e.emp_department)) = UPPER(d.dept_department_name)
  AND e.emp_department_id_dept IS NULL;

ALTER TABLE hrc_employee_mst DROP COLUMN IF EXISTS emp_department;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_emp_department_dept'
    ) THEN
        ALTER TABLE hrc_employee_mst
            ADD CONSTRAINT fk_emp_department_dept
            FOREIGN KEY (emp_department_id_dept) REFERENCES hrc_department_mst (dept_department_id);
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- 5) Menu: Department Master
-- ---------------------------------------------------------------------------
INSERT INTO sysm_menutree_mst (
    mtree_menu_code, mtree_menu_label, mtree_menu_group, mtree_sort_order, mtree_group_sort_order, mtree_icon, mtree_doc_type,
    mtree_supports_view, mtree_supports_create, mtree_supports_edit, mtree_supports_delete,
    mtree_supports_approve, mtree_supports_reject, mtree_supports_print, mtree_supports_export,
    mtree_is_system_menu, mtree_isactive, mtree_created_by, mtree_created_on
) VALUES
('DEPM', 'Department', 'Access & People', 36, 3, 'DEPM', NULL,
 TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, 'system', NOW())
ON CONFLICT (mtree_menu_code) DO UPDATE SET
    mtree_menu_label = EXCLUDED.mtree_menu_label,
    mtree_menu_group = EXCLUDED.mtree_menu_group,
    mtree_sort_order = EXCLUDED.mtree_sort_order,
    mtree_isactive = TRUE,
    mtree_modified_by = 'system',
    mtree_modified_on = NOW();

INSERT INTO sysm_rolepermission_dtl (
    rlpm_role_id_rol, rlpm_menu_id_mtree,
    rlpm_can_view, rlpm_can_create, rlpm_can_edit, rlpm_can_delete,
    rlpm_can_approve, rlpm_can_reject, rlpm_can_print, rlpm_can_export
)
SELECT
    r.rol_role_id, m.mtree_menu_id,
    TRUE,
    COALESCE(m.mtree_supports_create, FALSE),
    COALESCE(m.mtree_supports_edit, FALSE),
    COALESCE(m.mtree_supports_delete, FALSE),
    COALESCE(m.mtree_supports_approve, FALSE),
    COALESCE(m.mtree_supports_reject, FALSE),
    COALESCE(m.mtree_supports_print, FALSE),
    COALESCE(m.mtree_supports_export, FALSE)
FROM sysm_roles_mst r
CROSS JOIN sysm_menutree_mst m
WHERE UPPER(r.rol_role_code) = 'ADMIN' AND m.mtree_menu_code = 'DEPM'
  AND NOT EXISTS (
      SELECT 1 FROM sysm_rolepermission_dtl rp
      WHERE rp.rlpm_role_id_rol = r.rol_role_id AND rp.rlpm_menu_id_mtree = m.mtree_menu_id
  );
